Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 50

Naming/PredicateName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/BlockLength:
  Max: 50

Metrics/AbcSize:
  Max: 40
