class Schema::EmailReplyGeneratorSuggestions < Lockstep::ApiRecord

# ApiRecord will crash unless `id_ref` is defined
def self.id_ref
  nil
end

  # The kind of reply generated by the GMS Api
  # @type: string
  field :kind

  # The body of the reply generated by the GMS Api
  # @type: string
  field :body



end