class Schema::TransactionDetail < Lockstep::ApiRecord

# ApiRecord will crash unless `id_ref` is defined
def self.id_ref
  nil
end

  # Group account transaction detail is associated with.
  # @type: string
  # @format: uuid
  field :group_key

  # An additional reference number that is sometimes used to identify a transaction detail.
  # The meaning of this field is specific to the ERP or accounting system used by the user.
  # @type: string
  field :reference_number

  # The unique ID of the transaction detail record.
  # @type: string
  # @format: uuid
  field :transaction_detail_id

  # The unique ID of the entity applying the transaction to the transaction detail record.
  # @type: string
  # @format: uuid
  field :transaction_detail_applied_id

  # The unique ID of the transaction record.
  # @type: string
  # @format: uuid
  field :transaction_id

  # The type of the transaction detail record.
  #             
  # Recognized Invoice types are:
  # * `AR Invoice` - Represents an invoice sent by Company to the Customer
  # * `AP Invoice` - Represents an invoice sent by Vendor to the Company
  # * `AR Credit Memo` - Represents a credit memo generated by Company given to Customer
  # * `AP Credit Memo` - Represents a credit memo generated by Vendor given to Company
  #             
  # Recognized PaymentType values are:
  # * `AR Payment` - A payment made by a Customer to the Company
  # * `AP Payment` - A payment made by the Company to a Vendor
  # @type: string
  field :transaction_type

  # Additional type categorization of the transaction.
  # @type: string
  field :transaction_sub_type

  # The date when a transaction detail record was reported.
  # @type: string
  # @format: date-time
  field :transaction_date, Types::Params::DateTime

  # The total value of this transaction detail, inclusive or all taxes and line items.
  # @type: number
  # @format: double
  field :transaction_amount

  # The remaining balance of this transaction detail.
  # @type: number
  # @format: double
  field :outstanding_amount

  # Specific transactions have support for pdf retrieval from their respective erp. When this flag is true, an additional
  # call to Invoices/{id}/pdf or Payments/{id}/pdf can be made to retrieve a pdf directly from the erp.
  # @type: boolean
  field :supports_erp_pdf_retrieval



end